apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: neslihanhemosoftvscode 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neslihanhemosoftvscode 
    spec:
      containers:
        - name: neslihanhemosoftvscode 
          image: hemosoft.azurecr.io/neslihanhemosoftvscode
          ports:
          - containerPort: 80